# Generated by Django 3.0.3 on 2020-02-05 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaCreacion', models.DateField(auto_created=True, verbose_name='Fecha de creacion')),
                ('CodigoCargo', models.CharField(max_length=10, verbose_name='Código de cargo')),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.CharField(max_length=15, verbose_name='Número de cédula')),
                ('NoInss', models.IntegerField(verbose_name='Número de INSS')),
                ('CuentaBanco', models.IntegerField(blank=True, null=True, verbose_name='Número de cuenta bancaria')),
                ('Nombres', models.CharField(max_length=30)),
                ('PrimerApellido', models.CharField(max_length=30, verbose_name='Primer apellido')),
                ('SegundoApellido', models.CharField(blank=True, max_length=25, null=True, verbose_name='Segundo apellido')),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('EstadoCivil', models.CharField(choices=[('1', 'Soltero/a'), ('2', 'Comprometido/a'), ('3', 'En Relación'), ('4', 'Casado/a'), ('5', 'Unión libre'), ('6', 'Separado/a'), ('7', 'Viudo/a')], max_length=1)),
                ('Email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('Estado', models.BooleanField(default=True, verbose_name='Activo en el sistema')),
                ('Direccion', models.TextField()),
                ('TipoEmpleado', models.CharField(max_length=50)),
                ('GradoAcademico', models.CharField(choices=[('1', 'Bachiller'), ('2', 'Tecnico'), ('3', 'Egresado'), ('4', 'Ingeniero'), ('5', 'Licenciatura'), ('6', 'Maestría'), ('7', 'Especialidad'), ('8', 'Doctorado')], max_length=1)),
                ('Observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=10)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SalarioEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAsignacion', models.DateField(verbose_name='Fecha de asignación')),
                ('Monto', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Activo', models.BooleanField(default=True, verbose_name='Salario activo')),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomina.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaMovimiento', models.DateField(verbose_name='Fecha del movimiento')),
                ('Concepto', models.CharField(max_length=200)),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomina.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='FotosEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto', models.ImageField(upload_to='EmpleadosImagen', verbose_name='Imagen Empleado')),
                ('Activa', models.BooleanField(verbose_name='Foto actual')),
                ('Fecha', models.DateField(verbose_name='Fecha de creación')),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomina.Empleado', verbose_name='Propietario')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desde', models.DateField(verbose_name='Fecha inicial del cargo')),
                ('Hasta', models.DateField(null=True, verbose_name='Fecha final del cargo')),
                ('Cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomina.Cargo')),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomina.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto', models.DecimalField(decimal_places=4, max_digits=10)),
                ('AplicaDeduccion', models.BooleanField(default=False, verbose_name='Aplicar deducción')),
                ('TipoMovimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomina.TipoMovimiento', verbose_name='Tipo de movimiento')),
            ],
        ),
    ]
