# Generated by Django 3.0.3 on 2020-02-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomina', '0002_auto_20200207_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Cedula',
            field=models.CharField(max_length=16, verbose_name='Número de cédula'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='CuentaBanco',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cuenta bancaria'),
        ),
    ]
