# Generated by Django 3.0.3 on 2020-02-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomina', '0003_auto_20200207_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Observaciones',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
